//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDStore.addCategoryServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="addCategoryServiceReference1.addCategorySoap")]
    public interface addCategorySoap {
        
        // CODEGEN: Generating message contract since element name CategoryId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        DDStore.addCategoryServiceReference1.insertCategoryResponse insertCategory(DDStore.addCategoryServiceReference1.insertCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<DDStore.addCategoryServiceReference1.insertCategoryResponse> insertCategoryAsync(DDStore.addCategoryServiceReference1.insertCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCategory", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.addCategoryServiceReference1.insertCategoryRequestBody Body;
        
        public insertCategoryRequest() {
        }
        
        public insertCategoryRequest(DDStore.addCategoryServiceReference1.insertCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CategoryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CategoryName;
        
        public insertCategoryRequestBody() {
        }
        
        public insertCategoryRequestBody(string CategoryId, string CategoryName) {
            this.CategoryId = CategoryId;
            this.CategoryName = CategoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.addCategoryServiceReference1.insertCategoryResponseBody Body;
        
        public insertCategoryResponse() {
        }
        
        public insertCategoryResponse(DDStore.addCategoryServiceReference1.insertCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCategoryResult;
        
        public insertCategoryResponseBody() {
        }
        
        public insertCategoryResponseBody(string insertCategoryResult) {
            this.insertCategoryResult = insertCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface addCategorySoapChannel : DDStore.addCategoryServiceReference1.addCategorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addCategorySoapClient : System.ServiceModel.ClientBase<DDStore.addCategoryServiceReference1.addCategorySoap>, DDStore.addCategoryServiceReference1.addCategorySoap {
        
        public addCategorySoapClient() {
        }
        
        public addCategorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public addCategorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addCategorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addCategorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DDStore.addCategoryServiceReference1.insertCategoryResponse DDStore.addCategoryServiceReference1.addCategorySoap.insertCategory(DDStore.addCategoryServiceReference1.insertCategoryRequest request) {
            return base.Channel.insertCategory(request);
        }
        
        public string insertCategory(string CategoryId, string CategoryName) {
            DDStore.addCategoryServiceReference1.insertCategoryRequest inValue = new DDStore.addCategoryServiceReference1.insertCategoryRequest();
            inValue.Body = new DDStore.addCategoryServiceReference1.insertCategoryRequestBody();
            inValue.Body.CategoryId = CategoryId;
            inValue.Body.CategoryName = CategoryName;
            DDStore.addCategoryServiceReference1.insertCategoryResponse retVal = ((DDStore.addCategoryServiceReference1.addCategorySoap)(this)).insertCategory(inValue);
            return retVal.Body.insertCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DDStore.addCategoryServiceReference1.insertCategoryResponse> DDStore.addCategoryServiceReference1.addCategorySoap.insertCategoryAsync(DDStore.addCategoryServiceReference1.insertCategoryRequest request) {
            return base.Channel.insertCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<DDStore.addCategoryServiceReference1.insertCategoryResponse> insertCategoryAsync(string CategoryId, string CategoryName) {
            DDStore.addCategoryServiceReference1.insertCategoryRequest inValue = new DDStore.addCategoryServiceReference1.insertCategoryRequest();
            inValue.Body = new DDStore.addCategoryServiceReference1.insertCategoryRequestBody();
            inValue.Body.CategoryId = CategoryId;
            inValue.Body.CategoryName = CategoryName;
            return ((DDStore.addCategoryServiceReference1.addCategorySoap)(this)).insertCategoryAsync(inValue);
        }
    }
}
