//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDStore.loginServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="loginServiceReference1.LoginSoap")]
    public interface LoginSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AttemptLogin", ReplyAction="*")]
        DDStore.loginServiceReference1.AttemptLoginResponse AttemptLogin(DDStore.loginServiceReference1.AttemptLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AttemptLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<DDStore.loginServiceReference1.AttemptLoginResponse> AttemptLoginAsync(DDStore.loginServiceReference1.AttemptLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttemptLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttemptLogin", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.loginServiceReference1.AttemptLoginRequestBody Body;
        
        public AttemptLoginRequest() {
        }
        
        public AttemptLoginRequest(DDStore.loginServiceReference1.AttemptLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AttemptLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AttemptLoginRequestBody() {
        }
        
        public AttemptLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttemptLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttemptLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.loginServiceReference1.AttemptLoginResponseBody Body;
        
        public AttemptLoginResponse() {
        }
        
        public AttemptLoginResponse(DDStore.loginServiceReference1.AttemptLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AttemptLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AttemptLoginResult;
        
        public AttemptLoginResponseBody() {
        }
        
        public AttemptLoginResponseBody(string AttemptLoginResult) {
            this.AttemptLoginResult = AttemptLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSoapChannel : DDStore.loginServiceReference1.LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<DDStore.loginServiceReference1.LoginSoap>, DDStore.loginServiceReference1.LoginSoap {
        
        public LoginSoapClient() {
        }
        
        public LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DDStore.loginServiceReference1.AttemptLoginResponse DDStore.loginServiceReference1.LoginSoap.AttemptLogin(DDStore.loginServiceReference1.AttemptLoginRequest request) {
            return base.Channel.AttemptLogin(request);
        }
        
        public string AttemptLogin(string username, string password) {
            DDStore.loginServiceReference1.AttemptLoginRequest inValue = new DDStore.loginServiceReference1.AttemptLoginRequest();
            inValue.Body = new DDStore.loginServiceReference1.AttemptLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            DDStore.loginServiceReference1.AttemptLoginResponse retVal = ((DDStore.loginServiceReference1.LoginSoap)(this)).AttemptLogin(inValue);
            return retVal.Body.AttemptLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DDStore.loginServiceReference1.AttemptLoginResponse> DDStore.loginServiceReference1.LoginSoap.AttemptLoginAsync(DDStore.loginServiceReference1.AttemptLoginRequest request) {
            return base.Channel.AttemptLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<DDStore.loginServiceReference1.AttemptLoginResponse> AttemptLoginAsync(string username, string password) {
            DDStore.loginServiceReference1.AttemptLoginRequest inValue = new DDStore.loginServiceReference1.AttemptLoginRequest();
            inValue.Body = new DDStore.loginServiceReference1.AttemptLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((DDStore.loginServiceReference1.LoginSoap)(this)).AttemptLoginAsync(inValue);
        }
    }
}
