//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDStore.registerServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="registerServiceReference1.registerUserSoap")]
    public interface registerUserSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        DDStore.registerServiceReference1.addUserResponse addUser(DDStore.registerServiceReference1.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<DDStore.registerServiceReference1.addUserResponse> addUserAsync(DDStore.registerServiceReference1.addUserRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createUser", ReplyAction="*")]
        DDStore.registerServiceReference1.createUserResponse createUser(DDStore.registerServiceReference1.createUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createUser", ReplyAction="*")]
        System.Threading.Tasks.Task<DDStore.registerServiceReference1.createUserResponse> createUserAsync(DDStore.registerServiceReference1.createUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.registerServiceReference1.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(DDStore.registerServiceReference1.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(string UserName, string Phone, string Email, string FullName, string Address, string Password) {
            this.UserName = UserName;
            this.Phone = Phone;
            this.Email = Email;
            this.FullName = FullName;
            this.Address = Address;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.registerServiceReference1.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(DDStore.registerServiceReference1.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addUserResult;
        
        public addUserResponseBody() {
        }
        
        public addUserResponseBody(string addUserResult) {
            this.addUserResult = addUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUser", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.registerServiceReference1.createUserRequestBody Body;
        
        public createUserRequest() {
        }
        
        public createUserRequest(DDStore.registerServiceReference1.createUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UserType;
        
        public createUserRequestBody() {
        }
        
        public createUserRequestBody(string UserName, string Phone, string Email, string FullName, string Address, string Password, string UserType) {
            this.UserName = UserName;
            this.Phone = Phone;
            this.Email = Email;
            this.FullName = FullName;
            this.Address = Address;
            this.Password = Password;
            this.UserType = UserType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DDStore.registerServiceReference1.createUserResponseBody Body;
        
        public createUserResponse() {
        }
        
        public createUserResponse(DDStore.registerServiceReference1.createUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createUserResult;
        
        public createUserResponseBody() {
        }
        
        public createUserResponseBody(string createUserResult) {
            this.createUserResult = createUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface registerUserSoapChannel : DDStore.registerServiceReference1.registerUserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class registerUserSoapClient : System.ServiceModel.ClientBase<DDStore.registerServiceReference1.registerUserSoap>, DDStore.registerServiceReference1.registerUserSoap {
        
        public registerUserSoapClient() {
        }
        
        public registerUserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public registerUserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public registerUserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public registerUserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DDStore.registerServiceReference1.addUserResponse DDStore.registerServiceReference1.registerUserSoap.addUser(DDStore.registerServiceReference1.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public string addUser(string UserName, string Phone, string Email, string FullName, string Address, string Password) {
            DDStore.registerServiceReference1.addUserRequest inValue = new DDStore.registerServiceReference1.addUserRequest();
            inValue.Body = new DDStore.registerServiceReference1.addUserRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Phone = Phone;
            inValue.Body.Email = Email;
            inValue.Body.FullName = FullName;
            inValue.Body.Address = Address;
            inValue.Body.Password = Password;
            DDStore.registerServiceReference1.addUserResponse retVal = ((DDStore.registerServiceReference1.registerUserSoap)(this)).addUser(inValue);
            return retVal.Body.addUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DDStore.registerServiceReference1.addUserResponse> DDStore.registerServiceReference1.registerUserSoap.addUserAsync(DDStore.registerServiceReference1.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<DDStore.registerServiceReference1.addUserResponse> addUserAsync(string UserName, string Phone, string Email, string FullName, string Address, string Password) {
            DDStore.registerServiceReference1.addUserRequest inValue = new DDStore.registerServiceReference1.addUserRequest();
            inValue.Body = new DDStore.registerServiceReference1.addUserRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Phone = Phone;
            inValue.Body.Email = Email;
            inValue.Body.FullName = FullName;
            inValue.Body.Address = Address;
            inValue.Body.Password = Password;
            return ((DDStore.registerServiceReference1.registerUserSoap)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DDStore.registerServiceReference1.createUserResponse DDStore.registerServiceReference1.registerUserSoap.createUser(DDStore.registerServiceReference1.createUserRequest request) {
            return base.Channel.createUser(request);
        }
        
        public string createUser(string UserName, string Phone, string Email, string FullName, string Address, string Password, string UserType) {
            DDStore.registerServiceReference1.createUserRequest inValue = new DDStore.registerServiceReference1.createUserRequest();
            inValue.Body = new DDStore.registerServiceReference1.createUserRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Phone = Phone;
            inValue.Body.Email = Email;
            inValue.Body.FullName = FullName;
            inValue.Body.Address = Address;
            inValue.Body.Password = Password;
            inValue.Body.UserType = UserType;
            DDStore.registerServiceReference1.createUserResponse retVal = ((DDStore.registerServiceReference1.registerUserSoap)(this)).createUser(inValue);
            return retVal.Body.createUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DDStore.registerServiceReference1.createUserResponse> DDStore.registerServiceReference1.registerUserSoap.createUserAsync(DDStore.registerServiceReference1.createUserRequest request) {
            return base.Channel.createUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<DDStore.registerServiceReference1.createUserResponse> createUserAsync(string UserName, string Phone, string Email, string FullName, string Address, string Password, string UserType) {
            DDStore.registerServiceReference1.createUserRequest inValue = new DDStore.registerServiceReference1.createUserRequest();
            inValue.Body = new DDStore.registerServiceReference1.createUserRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Phone = Phone;
            inValue.Body.Email = Email;
            inValue.Body.FullName = FullName;
            inValue.Body.Address = Address;
            inValue.Body.Password = Password;
            inValue.Body.UserType = UserType;
            return ((DDStore.registerServiceReference1.registerUserSoap)(this)).createUserAsync(inValue);
        }
    }
}
